# Generated by Django 4.2.8 on 2024-02-01 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('catering_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('cuisine_type', models.CharField(max_length=255)),
                ('number_of_people', models.PositiveIntegerField()),
                ('availability_status', models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1)),
                ('rate_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('entertainment_id', models.AutoField(primary_key=True, serialize=False)),
                ('entertainment_type', models.CharField(choices=[('music', 'Music'), ('comedy', 'Comedy'), ('magic', 'Magic'), ('dance', 'Dance'), ('other', 'Other')], default='other', max_length=10)),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('availability', models.BooleanField(default=True)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('availability_status', models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('catering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.catering')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entertainment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.entertainment')),
                ('guest_list', models.ManyToManyField(blank=True, to='catalog.guest')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.transport')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.venue')),
            ],
        ),
    ]
