# Generated by Django 4.2.8 on 2024-02-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_venue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='type',
        ),
        migrations.AddField(
            model_name='transport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='venue_images/'),
        ),
    ]
