# Generated by Django 4.2.8 on 2024-02-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_transport_type_transport_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainment',
            name='availability',
        ),
        migrations.AddField(
            model_name='entertainment',
            name='availability_status',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='transport',
            name='availability_status',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1),
        ),
    ]
