# Generated by Django 4.2.8 on 2024-02-05 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_transport_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='service_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
