# Generated by Django 4.2.8 on 2024-02-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0008_entertainment_service_name_entertainment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering',
            name='menu',
            field=models.ImageField(blank=True, null=True, upload_to='venue_images/'),
        ),
        migrations.AddField(
            model_name='catering',
            name='menu2',
            field=models.ImageField(blank=True, null=True, upload_to='venue_images/'),
        ),
        migrations.AddField(
            model_name='catering',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
