# Generated by Django 4.2.8 on 2024-02-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_bookcatering'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcatering',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
