# Generated by Django 4.2.8 on 2024-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_bookentertainment_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookentertainment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
