# Generated by Django 4.2.8 on 2024-02-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_bookentertainment_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
